{% set name = "machinevision-toolbox-python" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 01a2fea34ec644eba98c7aebb3840ea3512dd9d5a4d005a41c9e8a6c27399e0a

build:
  noarch: python
  script: echo "${PKG_VERSION}" > RELEASE && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <2
    - scipy
    - matplotlib-base
    - py-opencv
    - spatialmath-python
    - pgraph-python
    - ansitable
    - mvtb-data
    - arm_pyart

test:
  requires:
    - python {{ python_min }}
  imports:
    - machinevisiontoolbox
  # fails because of opencv-contrib-python
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/petercorke/machinevision-toolbox-python
  summary: A machine vision for education and research
  dev_url: https://github.com/petercorke/machinevision-toolbox-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
